### ISSUE TITLE
Mututal SSL enabling as default SSL method when it's enabled

### ISSUE THREAD

**Issue by 7slcode7** [siddhi-io/siddhi-io-grpc#20]
**Description:**

We need to give both trust store and key store files when we are enabling SSL. Better if there is a possibility to enable one-way SSL (only client side server validation) by giving only a trust store file from the client side.

**Comment by sahandilshan** [comment]
Resolve this issue in https://github.com/siddhi-io/siddhi-io-grpc/pull/24.
