### ISSUE TITLE
Error occures when siddhi stream's attribute defined with an underscore

### ISSUE THREAD

**Issue by 7slcode7** [siddhi-io/siddhi-io-grpc#27]
**Description:**

- If there is a Siddhi stream attribute with an underscore mark, then below error occurs when app is going to get deployed. (with gRPC custom proto files)

![image](https://user-images.githubusercontent.com/40932779/70142624-b2a5db00-16bf-11ea-83c0-a185628a36da.png)

**============**

![image](https://user-images.githubusercontent.com/40932779/70142596-9c981a80-16bf-11ea-9c7f-e162789e027a.png)

**Comment by sahandilshan** [comment]
@7slcode7 this is an issue related to siddhi-map-protobuf, This issue occurred at the mapping level, not in the io-grpc level. Anyway this issue is fixed by https://github.com/siddhi-io/siddhi-map-protobuf/pull/13
